name:                techlab
version:             0.1.2.0
git:                 https://gitlab.com/homotopic-tech/
license:             MIT
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "2020 Daniel Firth"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Bleeding edge prelude
category:            Prelude

dependencies:
- base >= 4.7 && < 5
- chassis
- composite-base
- composite-dhall
- containers
- dhall
- first-class-families
- formatting
- optics == 0.4
- path-dhall-instance
- polysemy
- polysemy-extra
- polysemy-fs
- polysemy-kvstore >= 0.1.0.0 && < 0.2
- polysemy-path >= 0.2.0.0 && < 0.3
- polysemy-methodology >= 0.2.0.0 && < 0.3
- polysemy-methodology-composite
- polysemy-vinyl

library:
  source-dirs: src
