resolver: nightly-2021-07-23
packages:
- .
extra-deps:
- composite-dhall-0.0.1.0
- chassis-0.0.5.0
- git: https://github.com/locallycompact/composite
  commit: 5644183439960e63d06ef8ec5e85c25356c6b1fc
  subdirs:
  - composite-base
- polysemy-several-0.1.0.0
- polysemy-path-0.2.1.0
- polysemy-methodology-0.2.0.0
- polysemy-methodology-composite-0.1.4.0
allow-newer: true
nix:
  packages: [zlib]
  enable: false
  pure: false
